### PR TITLE
feat: get post comments, without following logic

### PR DESCRIPTION
**Pull request by santannaizadora**

### CODE REVIEW

**Comment by santannaizadora** [comment]
Por enquanto o endpoint que retorna os comentarios de um post está enviando um objeto nesse formato:
{
  "totalComments": 2,
  "comments": [
    {
      "id": "1",
      "userId": "2",
      "text": "a",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "isPostAuthor": false
    },
    {
      "id": "2",
      "userId": "2",
      "text": "a",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "isPostAuthor": false
    }
  ]
}

**Comment by santannaizadora** [comment]
Falta verificar se o usuário logado segue quem fez o comentário

**Comment by santannaizadora** [comment]
O objeto que está sendo retornado é o seguinte: 

{
  "totalComments": 8,
  "comments": [
    {
      "id": "1",
      "userId": "2",
      "text": "a",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": false,
      "isPostAuthor": false
    },
    {
      "id": "2",
      "userId": "2",
      "text": "a",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": false,
      "isPostAuthor": false
    },
    {
      "id": "3",
      "userId": "2",
      "text": "a",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": false,
      "isPostAuthor": false
    },
    {
      "id": "4",
      "userId": "5",
      "text": "b",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": true,
      "isPostAuthor": true
    },
    {
      "id": "5",
      "userId": "5",
      "text": "b",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": true,
      "isPostAuthor": true
    },
    {
      "id": "6",
      "userId": "3",
      "text": "c",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": true,
      "isPostAuthor": false
    },
    {
      "id": "7",
      "userId": "3",
      "text": "c",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": true,
      "isPostAuthor": false
    },
    {
      "id": "8",
      "userId": "4",
      "text": "d",
      "createdAt": "2022-06-22T23:50:56.428Z",
      "userIsFollowed": false,
      "isPostAuthor": false
    }
  ]
}

**Comment by estevamfurtado** [comment]
Esses dados já são acessados no front de outra forma.

**Pull request closed without merging**
